version: "3"

networks:
  zeebe_network:
    driver: bridge

volumes:
  zeebe_broker1_data: {}
  zeebe_broker2_data: {}
  zeebe_broker3_data: {}
  zeebe_elasticsearch_data: {}

services:  
  zeebe_node0:
    container_name: zeebe-broker1
    image: camunda/zeebe:0.25.1
    environment:
      - ZEEBE_LOG_LEVEL=INFO
      - ZEEBE_BROKER_CLUSTER_NODEID=0
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=3
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe_node0:26502
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
    networks:
      - zeebe_network
    volumes:
      - zeebe_broker1_data:/usr/local/zeebe/data
    depends_on:
      - elasticsearch
    restart: always
  zeebe_node1:
    container_name: zeebe-broker2
    image: camunda/zeebe:0.25.1
    environment:
      - ZEEBE_LOG_LEVEL=INFO
      - ZEEBE_BROKER_CLUSTER_NODEID=1
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=3
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe_node0:26502
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
    networks:
      - zeebe_network    
    volumes:
      - zeebe_broker2_data:/usr/local/zeebe/data      
    depends_on:
      - elasticsearch
      - zeebe_node0
    restart: always
  zeebe_node2:
    container_name: zeebe-broker3
    image: camunda/zeebe:0.25.1
    environment:
      - ZEEBE_LOG_LEVEL=INFO
      - ZEEBE_BROKER_CLUSTER_NODEID=2
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=3
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe_node0:26502
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
    networks:
      - zeebe_network
    volumes:
      - zeebe_broker3_data:/usr/local/zeebe/data
    depends_on:
      - elasticsearch
      - zeebe_node0
    restart: always
  zeebe_gateway:
    container_name: zeebe-gateway
    image: camunda/zeebe:0.25.1
    environment:
      - ZEEBE_LOG_LEVEL=INFO
      - ZEEBE_STANDALONE_GATEWAY=true
      - ZEEBE_GATEWAY_NETWORK_HOST=0.0.0.0
      - ZEEBE_GATEWAY_NETWORK_PORT=26500
      - ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT=zeebe_node0:26502
      - ZEEBE_GATEWAY_CLUSTER_HOST=zeebe_gateway
      - ZEEBE_GATEWAY_CLUSTER_PORT=26502      
    ports:
      - "26500:26500"      
    networks:
      - zeebe_network
    depends_on:
      - zeebe_node0
    restart: always
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
    volumes:
      - zeebe_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - zeebe_network
    restart: always
  operate:
    container_name: operate
    image: camunda/operate:0.25.0
    ports:
      - "8080:8080"
    depends_on:
      - zeebe_node0
      - zeebe_node1
      - zeebe_node2
      - zeebe_gateway
      - elasticsearch
    volumes:
      - ./operate-config.yml:/usr/local/operate/config/application.yml
    networks:
      - zeebe_network
    restart: always